### ISSUE TITLE
Clarification for Video Backdrops

### ISSUE THREAD

**Issue by justbest23** [ShiniGandhi/JellyTheme#6]
Heyo

I've just been exploring the themes section and I'm loving this layout. I'm not understanding how to use the video backdrops feature though.

Do I need to have a backdrops folder within each movie folder? Or can it be a central folder somewhere? And can I automate the downloading of trailers into these folders?

Additionally, when using the picture backdrops I'm seeing transparency issues, where the previous image is behind the new image, like so:
![image](https://user-images.githubusercontent.com/73498310/219058307-d23c6966-4a96-4b85-9818-4a1256108597.png)
![image](https://user-images.githubusercontent.com/73498310/219058353-471ec572-de36-4eb3-97a9-9342eec05d46.png)

Any help is greatly appreciated! Thanks!

**Comment by Amarel-LTD** [comment]
Are you using [JellyTheme.css](https://github.com/ShiniGandhi/JellyTheme/blob/main/latest/JellyTheme.css) or [JellyTheme-Cleaner.css](https://github.com/ShiniGandhi/JellyTheme/blob/main/latest/JellyTheme-Cleaner.css)?

**Comment by TroggoMan** [comment]
JellyTheme.css. You're speedy with your replies!

Specifically running:
```
@import url('https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@latest/latest/JellyTheme.css'); 
/* JellyTheme */:root {--accent:rgba(98.00787045,121.00999580324999,204.99450000000002,1)!important;}
```

**Comment by Amarel-LTD** [comment]
I'm currently on a computer so yeah 😅
In any case, I'll have a look at it later today, there might be some issue with how I've layered things.
I'll let you know when I have a fix.

**Comment by TroggoMan** [comment]
Great! Thanks! 

Also, I know it's nothing to do with your theme, but do you have any idea how to slow down the screensaver slideshow? It changes images every 3 seconds, waaaaay too fast!

**Comment by Amarel-LTD** [comment]
Can you try using `@import url('https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@v2.9.1/latest/JellyTheme.css');` and let me know if it still causes issues?

As for the video backdrops, you need to have a video file in a directory called `backdrops` in each movie/show's directory. So for example `/movies/movie (2019)/backdrops/whatever.mp4`. The file can be in any video extension that jellyfin supports.
If you want to automate it, I have a tool that I made called [Backdroppr](https://github.com/ShiniGandhi/Backdroppr), which does just that.

As for the slideshow speed, I'm not sure tbh.

**Comment by TroggoMan** [comment]
Heyo.

The transparency is still an issue. Same as before.

I was testing this on my desktop before and I then moved to my Media PC (which is at 125% scaling cuz smol) and the theme was very broken. I presume the 125% scaling is what's breaking it. Even the default JellyFin app breaks when I go to 150%.

The UI elements were all over the place, all of the text from the movies/shows stripe was condensed into the middle of the screen. When trying to play anything the screen would just be black, but audio would play.

I can test it again on the media PC with the new config and give feedback. Will try your Backdroppr now too, as that's first prize anyway!

**Comment by Amarel-LTD** [comment]
Yeah the scaling is a bit of a mess, I need to rework the whole thing at some point.
As for the desktop app, that's something I'm aware of, but haven't found a way to fix it yet.

**Comment by Amarel-LTD** [comment]
I just pushed out a fix for the backdrop thing, let me know if it fixed it (manually switch to the new version)
```
@import url('https://cdn.jsdelivr.net/gh/ShiniGandhi/JellyTheme@v2.10.3/latest/JellyTheme.css');
```

**Comment by TroggoMan** [comment]
Still the same issue. Maybe it's on my side? Idk 

![image](https://user-images.githubusercontent.com/73498310/219944129-2cde9ca1-bbc3-4b98-89b6-4a06bc2ee4c2.png)

**Comment by Amarel-LTD** [comment]
It might be. Can you send me all of your custom css?

**Comment by TroggoMan** [comment]
That line you sent is the only line in the custom CSS box.

**Comment by ausar47** [comment]
> It might be. Can you send me all of your custom css?

I've got the same issue with the lastest JellyTheme version on Jellyfin Desktop. Yet the latest JellyTheme-Cleaner version has no such issue, maybe you could check that out.

**Comment by Amarel-LTD** [comment]
I haven't had time to work on this, but hopefully tomorrow.

In any case, I'll keep you posted on that.

**Comment by ghost** [comment]
huge delay, but i was really busy with work unfortunately.
is this still happening? if so, i can't seem to make it happen on my clients

**Comment by TroggoMan** [comment]
Heyo. Yea seems to be all good now on my side!

**Comment by ghost** [comment]
nice :D
